//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAttribute
{
    public int id { get; set; }
    public string itemType { get; set; }
    public string name { get; set; }
    public Nullable<double> Latitude { get; set; }
    public Nullable<double> Longitude { get; set; }
    public string sub1 { get; set; }
    public string sub2 { get; set; }
    public string sub3 { get; set; }
    public string sub4 { get; set; }
    public string sub5 { get; set; }
}

public partial class tblLocation
{
    public int LocationID { get; set; }
    public string LocationDescription { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string Town { get; set; }
    public string County { get; set; }
    public string Postcode { get; set; }
    public string Country { get; set; }
    public decimal Latitude { get; set; }
    public decimal Longitude { get; set; }
}

public partial class tblPlace
{
    public int id { get; set; }
    public Nullable<double> Latitude { get; set; }
    public Nullable<double> Longitude { get; set; }
    public string Description { get; set; }
}

public partial class tblUnitsGP
{
    public int id { get; set; }
    public Nullable<int> unitId { get; set; }
    public Nullable<double> lat { get; set; }
    public Nullable<double> @long { get; set; }
    public Nullable<double> accuracy { get; set; }
    public Nullable<double> min_speed { get; set; }
    public Nullable<double> max_speed { get; set; }
    public Nullable<System.DateTime> appended_datetime { get; set; }
    public Nullable<int> code { get; set; }
    public string note { get; set; }
}
