//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;

public partial class DB_14781_schoolsEntities : DbContext
{
    public DB_14781_schoolsEntities()
        : base("name=DB_14781_schoolsEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<tblAttribute> tblAttributes { get; set; }
    public DbSet<tblLocation> tblLocations { get; set; }
    public DbSet<tblPlace> tblPlaces { get; set; }
    public DbSet<tblUnitsGP> tblUnitsGPS { get; set; }

    public virtual int GetNearbyLocations(Nullable<int> distance, Nullable<double> latitude, Nullable<double> longitude)
    {
        var distanceParameter = distance.HasValue ?
            new ObjectParameter("Distance", distance) :
            new ObjectParameter("Distance", typeof(int));

        var latitudeParameter = latitude.HasValue ?
            new ObjectParameter("Latitude", latitude) :
            new ObjectParameter("Latitude", typeof(double));

        var longitudeParameter = longitude.HasValue ?
            new ObjectParameter("Longitude", longitude) :
            new ObjectParameter("Longitude", typeof(double));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetNearbyLocations", distanceParameter, latitudeParameter, longitudeParameter);
    }

    public virtual ObjectResult<string> proc_Location_List(Nullable<decimal> dmlLat, Nullable<decimal> dmlLng, Nullable<int> intRadius)
    {
        var dmlLatParameter = dmlLat.HasValue ?
            new ObjectParameter("dmlLat", dmlLat) :
            new ObjectParameter("dmlLat", typeof(decimal));

        var dmlLngParameter = dmlLng.HasValue ?
            new ObjectParameter("dmlLng", dmlLng) :
            new ObjectParameter("dmlLng", typeof(decimal));

        var intRadiusParameter = intRadius.HasValue ?
            new ObjectParameter("intRadius", intRadius) :
            new ObjectParameter("intRadius", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_Location_List", dmlLatParameter, dmlLngParameter, intRadiusParameter);
    }
}
