//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblUnitsGP
{
    public int id { get; set; }
    public Nullable<int> unitId { get; set; }
    public Nullable<double> lat { get; set; }
    public Nullable<double> @long { get; set; }
    public Nullable<double> accuracy { get; set; }
    public Nullable<double> min_speed { get; set; }
    public Nullable<double> max_speed { get; set; }
    public Nullable<System.DateTime> appended_datetime { get; set; }
    public Nullable<int> code { get; set; }
    public string note { get; set; }
}
